server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iu?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: iu
    password: bitc5600
    
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
file:
  path: C:\src\springwork\mybatis-crud-project\src\main\webapp\images\
        